/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP3
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <UART.h>
#include <UART_RX.h>
#include <ADC.h>
#include <ADC_Clock.h>
#include <ADC_POS_aliases.h>
#include <ADC_POS.h>
#include <DMA_ADC_MEM_dma.h>
#include <TIMER_DMA.h>
#include <DMA_ENABLE.h>
#include <DMA_FRAME_READY.h>
#include <DAC_1.h>
#include <DAC_POS_aliases.h>
#include <DAC_POS.h>
#include <MUX_DAC.h>
#include <DAC_2.h>
#include <Control_DAC.h>
#include <UART_IntClock.h>
#include <ADC_IRQ.h>
#include <DAC_1_DacClk.h>
#include <DAC_1_Wave1_DMA_dma.h>
#include <DAC_1_Wave2_DMA_dma.h>
#include <DAC_1_VDAC8.h>
#include <DAC_2_DacClk.h>
#include <DAC_2_Wave1_DMA_dma.h>
#include <DAC_2_Wave2_DMA_dma.h>
#include <DAC_2_VDAC8.h>
#include <DAC_2_BuffAmp.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

